### ISSUE TITLE
streamID not working

### ISSUE THREAD

**Issue by GintautasMickus** [ThibaultBee/SRTWrapper#5]
Hello,

I have tried your SRTWrapper for android seems to work except  for streamID. I set it before making socket connection, but the reciever/listener does not get it... Any help would be appreciated.

**Comment by ThibaultBee** [comment]
Just to be sure we understand each other,  what you are doing is something like this:

- on client side: `socket.setSockFlag(SockOpt.STREAMID, "Hello")`
- on client side: connect to server
- on server side: onListen is trigger but streamId is empty
Is this what you are doing?

Have you tried `socket.getSockFlag(SockOpt.STREAMID)` on your server receiving socket when connection has been accepted by server?

**Comment by GintautasMickus** [comment]
Client:
if (this.srtSocket.setSockFlag(SockOpt.STREAMID, "Hello") != 0) {
                    this.srtSocket.close();
                    Thread.currentThread().interrupt();
                    return;
                    //throw new Exception("Failed to set sock flag to Sender: ${Utils.getErrorMessage()}");
                }
                if (this.srtSocket.connect(url, port) != 0) {
                    this.srtSocket.close();
                    Thread.currentThread().interrupt();
                    return;
                    //throw new Exception("Failed to connect to $ip:$port: ${Utils.getErrorMessage()}");
                }

Server:
hSock = srt_accept(listenfd, (struct sockaddr *)&clientaddr, &addrlen);
int st = srt_getsockflag(hSock, SRTO_STREAMID, (void*) msg, &addrlen);

st = 0 (no error)
addlen=0 (no message received)

**Comment by ThibaultBee** [comment]
Hey,

I just fixed it in https://github.com/ThibaultBee/SRTWrapper/tree/bugfix/setSockOpt
You can try to use the artifact from jitpack when build is completed:
`
	dependencies {
	        implementation 'com.github.ThibaultBee:SRTWrapper:bugfix~setSockOpt-0660d81bd0-1'
	}
`

If it is Ok with you, I will merge into master and create milestone 0.8.1.

**Comment by GintautasMickus** [comment]
I checked and now it works, thank you very much.
